title: Anakha Ajayakumar
logo: /assets/img/Portfolio DP.png
description: A Master's student in Industrial Mathematics and Data Analysis based in Bremen, Germany.
show_downloads: true
theme: jekyll-theme-minimal
